<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ItemOrder extends \App\Models\Doctrine\Entities\ItemOrder implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * {@inheritDoc}
     * @return array
     */
    public function __sleep()
    {
        $properties = array_merge(['__isInitialized__'], parent::__sleep());

        if ($this->__isInitialized__) {
            $properties = array_diff($properties, array_keys($this->__getLazyProperties()));
        }

        return $properties;
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ItemOrder $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deleted_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deleted_at]);

        return parent::setDeletedAt($deleted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMandante($mandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMandante', [$mandante]);

        return parent::setMandante($mandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getMandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandante', []);

        return parent::getMandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderId($order_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderId', [$order_id]);

        return parent::setOrderId($order_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', []);

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostId($cost_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostId', [$cost_id]);

        return parent::setCostId($cost_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostId', []);

        return parent::getCostId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductId($product_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductId', [$product_id]);

        return parent::setProductId($product_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductId', []);

        return parent::getProductId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyId($currency_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyId', [$currency_id]);

        return parent::setCurrencyId($currency_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyId', []);

        return parent::getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantidade($quantidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantidade', [$quantidade]);

        return parent::setQuantidade($quantidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantidade', []);

        return parent::getQuantidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUnitario($valor_unitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUnitario', [$valor_unitario]);

        return parent::setValorUnitario($valor_unitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUnitario', []);

        return parent::getValorUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontoUnitario($desconto_unitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontoUnitario', [$desconto_unitario]);

        return parent::setDescontoUnitario($desconto_unitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescontoUnitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescontoUnitario', []);

        return parent::getDescontoUnitario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', [$descricao]);

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', []);

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function addItemOrderSharedStat(\App\Models\Doctrine\Entities\ItemOrderSharedStat $itemOrderSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItemOrderSharedStat', [$itemOrderSharedStat]);

        return parent::addItemOrderSharedStat($itemOrderSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItemOrderSharedStat(\App\Models\Doctrine\Entities\ItemOrderSharedStat $itemOrderSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItemOrderSharedStat', [$itemOrderSharedStat]);

        return parent::removeItemOrderSharedStat($itemOrderSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemOrderSharedStats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemOrderSharedStats', []);

        return parent::getItemOrderSharedStats();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\App\Models\Doctrine\Entities\Order $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', [$order]);

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', []);

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostAllocate(\App\Models\Doctrine\Entities\CostAllocate $costAllocate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostAllocate', [$costAllocate]);

        return parent::setCostAllocate($costAllocate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostAllocate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostAllocate', []);

        return parent::getCostAllocate();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\App\Models\Doctrine\Entities\Product $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', [$product]);

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', []);

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setSharedCurrency(\App\Models\Doctrine\Entities\SharedCurrency $sharedCurrency = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSharedCurrency', [$sharedCurrency]);

        return parent::setSharedCurrency($sharedCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedCurrency', []);

        return parent::getSharedCurrency();
    }

}
