<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Models\Doctrine\Entities\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * {@inheritDoc}
     * @return array
     */
    public function __sleep()
    {
        $properties = array_merge(['__isInitialized__'], parent::__sleep());

        if ($this->__isInitialized__) {
            $properties = array_diff($properties, array_keys($this->__getLazyProperties()));
        }

        return $properties;
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deleted_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deleted_at]);

        return parent::setDeletedAt($deleted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMandante($mandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMandante', [$mandante]);

        return parent::setMandante($mandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getMandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandante', []);

        return parent::getMandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setUomId($uom_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUomId', [$uom_id]);

        return parent::setUomId($uom_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getUomId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUomId', []);

        return parent::getUomId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostId($cost_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostId', [$cost_id]);

        return parent::setCostId($cost_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostId', []);

        return parent::getCostId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setImagem($imagem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImagem', [$imagem]);

        return parent::setImagem($imagem);
    }

    /**
     * {@inheritDoc}
     */
    public function getImagem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagem', []);

        return parent::getImagem();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodFiscal($cod_fiscal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodFiscal', [$cod_fiscal]);

        return parent::setCodFiscal($cod_fiscal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodFiscal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodFiscal', []);

        return parent::getCodFiscal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodBarra($cod_barra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodBarra', [$cod_barra]);

        return parent::setCodBarra($cod_barra);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodBarra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodBarra', []);

        return parent::getCodBarra();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromocao($promocao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromocao', [$promocao]);

        return parent::setPromocao($promocao);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromocao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromocao', []);

        return parent::getPromocao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstoque($estoque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstoque', [$estoque]);

        return parent::setEstoque($estoque);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstoque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstoque', []);

        return parent::getEstoque();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUnitVenda($valorUnitVenda)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUnitVenda', [$valorUnitVenda]);

        return parent::setValorUnitVenda($valorUnitVenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUnitVenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUnitVenda', []);

        return parent::getValorUnitVenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUnitVendaPromocao($valorUnitVendaPromocao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUnitVendaPromocao', [$valorUnitVendaPromocao]);

        return parent::setValorUnitVendaPromocao($valorUnitVendaPromocao);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUnitVendaPromocao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUnitVendaPromocao', []);

        return parent::getValorUnitVendaPromocao();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorUnitCompra($valorUnitCompra)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorUnitCompra', [$valorUnitCompra]);

        return parent::setValorUnitCompra($valorUnitCompra);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorUnitCompra()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorUnitCompra', []);

        return parent::getValorUnitCompra();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldId($old_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldId', [$old_id]);

        return parent::setOldId($old_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldId', []);

        return parent::getOldId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstoqueMinimo($estoque_minimo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstoqueMinimo', [$estoque_minimo]);

        return parent::setEstoqueMinimo($estoque_minimo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstoqueMinimo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstoqueMinimo', []);

        return parent::getEstoqueMinimo();
    }

    /**
     * {@inheritDoc}
     */
    public function addItemOrder(\App\Models\Doctrine\Entities\ItemOrder $itemOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItemOrder', [$itemOrder]);

        return parent::addItemOrder($itemOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItemOrder(\App\Models\Doctrine\Entities\ItemOrder $itemOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItemOrder', [$itemOrder]);

        return parent::removeItemOrder($itemOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemOrders', []);

        return parent::getItemOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductProductGroup(\App\Models\Doctrine\Entities\ProductProductGroup $productProductGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductProductGroup', [$productProductGroup]);

        return parent::addProductProductGroup($productProductGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductProductGroup(\App\Models\Doctrine\Entities\ProductProductGroup $productProductGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductProductGroup', [$productProductGroup]);

        return parent::removeProductProductGroup($productProductGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductProductGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductProductGroups', []);

        return parent::getProductProductGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addProductSharedStat(\App\Models\Doctrine\Entities\ProductSharedStat $productSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProductSharedStat', [$productSharedStat]);

        return parent::addProductSharedStat($productSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProductSharedStat(\App\Models\Doctrine\Entities\ProductSharedStat $productSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProductSharedStat', [$productSharedStat]);

        return parent::removeProductSharedStat($productSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductSharedStats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductSharedStats', []);

        return parent::getProductSharedStats();
    }

    /**
     * {@inheritDoc}
     */
    public function setSharedUnitOfMeasure(\App\Models\Doctrine\Entities\SharedUnitOfMeasure $sharedUnitOfMeasure = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSharedUnitOfMeasure', [$sharedUnitOfMeasure]);

        return parent::setSharedUnitOfMeasure($sharedUnitOfMeasure);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedUnitOfMeasure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedUnitOfMeasure', []);

        return parent::getSharedUnitOfMeasure();
    }

    /**
     * {@inheritDoc}
     */
    public function setCostAllocate(\App\Models\Doctrine\Entities\CostAllocate $costAllocate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCostAllocate', [$costAllocate]);

        return parent::setCostAllocate($costAllocate);
    }

    /**
     * {@inheritDoc}
     */
    public function getCostAllocate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCostAllocate', []);

        return parent::getCostAllocate();
    }

}
