<?php

namespace DoctrineProxies\__CG__\App\Models\Doctrine\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \App\Models\Doctrine\Entities\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * {@inheritDoc}
     * @return array
     */
    public function __sleep()
    {
        $properties = array_merge(['__isInitialized__'], parent::__sleep());

        if ($this->__isInitialized__) {
            $properties = array_diff($properties, array_keys($this->__getLazyProperties()));
        }

        return $properties;
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($created_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$created_at]);

        return parent::setCreatedAt($created_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updated_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updated_at]);

        return parent::setUpdatedAt($updated_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeletedAt($deleted_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeletedAt', [$deleted_at]);

        return parent::setDeletedAt($deleted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeletedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeletedAt', []);

        return parent::getDeletedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setMandante($mandante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMandante', [$mandante]);

        return parent::setMandante($mandante);
    }

    /**
     * {@inheritDoc}
     */
    public function getMandante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMandante', []);

        return parent::getMandante();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerId($partner_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerId', [$partner_id]);

        return parent::setPartnerId($partner_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerId', []);

        return parent::getPartnerId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressId($address_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressId', [$address_id]);

        return parent::setAddressId($address_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', []);

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyId($currency_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyId', [$currency_id]);

        return parent::setCurrencyId($currency_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyId', []);

        return parent::getCurrencyId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeId($type_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeId', [$type_id]);

        return parent::setTypeId($type_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeId', []);

        return parent::getTypeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentId($payment_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentId', [$payment_id]);

        return parent::setPaymentId($payment_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentId', []);

        return parent::getPaymentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostedAt($posted_at)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostedAt', [$posted_at]);

        return parent::setPostedAt($posted_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostedAt', []);

        return parent::getPostedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorTotal($valor_total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorTotal', [$valor_total]);

        return parent::setValorTotal($valor_total);
    }

    /**
     * {@inheritDoc}
     */
    public function getValorTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorTotal', []);

        return parent::getValorTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescontoTotal($desconto_total)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescontoTotal', [$desconto_total]);

        return parent::setDescontoTotal($desconto_total);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescontoTotal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescontoTotal', []);

        return parent::getDescontoTotal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTroco($troco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTroco', [$troco]);

        return parent::setTroco($troco);
    }

    /**
     * {@inheritDoc}
     */
    public function getTroco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTroco', []);

        return parent::getTroco();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescricao($descricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescricao', [$descricao]);

        return parent::setDescricao($descricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescricao', []);

        return parent::getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferencia($referencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferencia', [$referencia]);

        return parent::setReferencia($referencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferencia', []);

        return parent::getReferencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setObsevacao($obsevacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObsevacao', [$obsevacao]);

        return parent::setObsevacao($obsevacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getObsevacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObsevacao', []);

        return parent::getObsevacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOldId($old_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOldId', [$old_id]);

        return parent::setOldId($old_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getOldId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOldId', []);

        return parent::getOldId();
    }

    /**
     * {@inheritDoc}
     */
    public function addAttachment(\App\Models\Doctrine\Entities\Attachment $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAttachment', [$attachment]);

        return parent::addAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAttachment(\App\Models\Doctrine\Entities\Attachment $attachment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAttachment', [$attachment]);

        return parent::removeAttachment($attachment);
    }

    /**
     * {@inheritDoc}
     */
    public function getAttachments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAttachments', []);

        return parent::getAttachments();
    }

    /**
     * {@inheritDoc}
     */
    public function addItemOrder(\App\Models\Doctrine\Entities\ItemOrder $itemOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItemOrder', [$itemOrder]);

        return parent::addItemOrder($itemOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItemOrder(\App\Models\Doctrine\Entities\ItemOrder $itemOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItemOrder', [$itemOrder]);

        return parent::removeItemOrder($itemOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemOrders', []);

        return parent::getItemOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderConfirmation(\App\Models\Doctrine\Entities\OrderConfirmation $orderConfirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderConfirmation', [$orderConfirmation]);

        return parent::addOrderConfirmation($orderConfirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderConfirmation(\App\Models\Doctrine\Entities\OrderConfirmation $orderConfirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderConfirmation', [$orderConfirmation]);

        return parent::removeOrderConfirmation($orderConfirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderConfirmations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderConfirmations', []);

        return parent::getOrderConfirmations();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderSharedStat(\App\Models\Doctrine\Entities\OrderSharedStat $orderSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderSharedStat', [$orderSharedStat]);

        return parent::addOrderSharedStat($orderSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderSharedStat(\App\Models\Doctrine\Entities\OrderSharedStat $orderSharedStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderSharedStat', [$orderSharedStat]);

        return parent::removeOrderSharedStat($orderSharedStat);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderSharedStats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderSharedStats', []);

        return parent::getOrderSharedStats();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner(\App\Models\Doctrine\Entities\Partner $partner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', [$partner]);

        return parent::setPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', []);

        return parent::getPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(\App\Models\Doctrine\Entities\Address $address = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setSharedCurrency(\App\Models\Doctrine\Entities\SharedCurrency $sharedCurrency = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSharedCurrency', [$sharedCurrency]);

        return parent::setSharedCurrency($sharedCurrency);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedCurrency', []);

        return parent::getSharedCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setSharedOrderType(\App\Models\Doctrine\Entities\SharedOrderType $sharedOrderType = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSharedOrderType', [$sharedOrderType]);

        return parent::setSharedOrderType($sharedOrderType);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedOrderType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedOrderType', []);

        return parent::getSharedOrderType();
    }

    /**
     * {@inheritDoc}
     */
    public function setSharedOrderPayment(\App\Models\Doctrine\Entities\SharedOrderPayment $sharedOrderPayment = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSharedOrderPayment', [$sharedOrderPayment]);

        return parent::setSharedOrderPayment($sharedOrderPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getSharedOrderPayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSharedOrderPayment', []);

        return parent::getSharedOrderPayment();
    }

}
